<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Кафе "Огнище"</title>
    <link rel=stylesheet type=text/css href='css/ADMIN_all.css'>
    <link rel=stylesheet type=text/css href='css/ADMIN_kontakty.css'>
    <link rel="shortcut icon" href="foto/iconka.png" />
</head>
<body>
<div id="headerline_first">
    <div>
        <div class="text_headerline"><img class="icon" src="foto/icon_1.png">д. Балдеевка,<br>ул. Уличная, 17А</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_2.png">Пн-Сб: 11:00-23:00<br>Вс: 11:00-01:00</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_3.png">+375 (88) 435-26-91<br>+375 (32) 632-73-16</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_4.png">Instagram:<br>ognische_real</div>
        <a id="vyiti_button" href="kontakty"><img src="foto/exit.png">Выйти</a>
    </div>
</div>
<div id="headerline_second">
    <div>
        <a class="a_headerline" href="ADMIN_menu">Меню</a>
        <a class="a_headerline" href="ADMIN_dostavka">Доставка и оплата</a>
        <a class="a_headerline" href="ADMIN_akcii">Акции</a>
        <a class="a_headerline" href="ADMIN_kontakty">Контакты</a>
        <a class="a_headerline" href="ADMIN_otzyvy">Отзывы</a>
    </div>
</div>
<a href="ADMIN_index"><img src="foto/logotip.png" id="logotip"></a>

<div id="name"><a1></a1><div class="zagolovok zagolovok_7">Контакты</div><a2></a2></div>

<div id="div_kontakty">
    <div id="kontakty_text">
        <div>
            <div class="abzac">&nbsp;Адрес&nbsp;<hr></div>
            <div class="text">д. Балдеевка, ул. Уличная, 17А</div>
            <div class="abzac">&nbsp;Время работы&nbsp;<hr></div>
            <div class="text">Пн-Чт, Вс: 11:00-23:00<br>Пт-Сб: 11:00-01:00</div>
        </div>
        <div id="My_na_karte">Мы на карте<img src="foto/strelka_2.png"></div>
    </div>
    <img id="foto_kontakty" src="foto/foto_1.png">
</div>



<div id="karta_adres"><script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Af70efe4be5ee0324e9cf8595fab08219ed8fe93712dd3bbfebd200f1aaf6a833&amp;width=100%25&amp;height=624&amp;lang=ru_RU&amp;scroll=true"></script></div>


<div id="footerline" style="margin: 0px;">© 2006-2023 ООО &#171;Огнище&#187;. Все права защищены</div>

<script src="js/ADMIN_all.js"></script>
</body>
</html>