<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Кафе "Огнище"</title>
    <link rel=stylesheet type=text/css href='css/ADMIN_all.css'>
    <link rel=stylesheet type=text/css href='css/ADMIN_dostavka.css'>
    <link rel="shortcut icon" href="foto/iconka.png" />
</head>
<body>
<div id="headerline_first">
    <div>
        <div class="text_headerline"><img class="icon" src="foto/icon_1.png">д. Балдеевка,<br>ул. Уличная, 17А</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_2.png">Пн-Сб: 11:00-23:00<br>Вс: 11:00-01:00</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_3.png">+375 (88) 435-26-91<br>+375 (32) 632-73-16</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_4.png">Instagram:<br>ognische_real</div>
        <a id="vyiti_button" href="dostavka"><img src="foto/exit.png">Выйти</a>
    </div>
</div>
<div id="headerline_second">
    <div>
        <a class="a_headerline" href="ADMIN_menu">Меню</a>
        <a class="a_headerline" href="ADMIN_dostavka">Доставка и оплата</a>
        <a class="a_headerline" href="ADMIN_akcii">Акции</a>
        <a class="a_headerline" href="ADMIN_kontakty">Контакты</a>
        <a class="a_headerline" href="ADMIN_otzyvy">Отзывы</a>
    </div>
</div>
<a href="ADMIN_index"><img src="foto/logotip.png" id="logotip"></a>

<div id="name"><a1></a1><div class="zagolovok zagolovok_5">Доставка и оплата</div><a2></a2></div>

<div id="dostavka_text">
    <div>
        <div class="abzac">&nbsp;Время доставки&nbsp;<hr></div>
        <div class="text">Заказы принимаются <b>с 11:00 до 19:00 ежедневно</b><br>Время доставки до <b>60 минут</b></div>
    </div>
    <div>
        <div class="abzac">&nbsp;Стоимость доставки&nbsp;<hr></div>
        <div class="text">Стоимость доставки <b>4 руб.</b><br>При заказе <b>от 30 руб. доставка бесплатная</b></div>
    </div>
</div>

<div id="pro_zakazy"><div>Заказы осуществляются по телефону <b>&nbsp;+375 (88) 435-26-91&nbsp;</b> или <b>&nbsp;+375 (32) 632-73-16&nbsp;</b></div></div>

<div id="Oblast_dostavki_div"><div id="Oblast_dostavki">Область доставки<img src="foto/strelka_2.png"></div></div>

<div id="karta_oblast"><script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A827a20125979e42f7bf01f0a86c5469e288a4c6bb2c0396fe21f1f160fee63ce&amp;width=100%25&amp;height=583&amp;lang=ru_RU&amp;scroll=true"></script></div>

<div id="footerline" style="margin: 0px;">© 2006-2023 ООО &#171;Огнище&#187;. Все права защищены</div>

<script src="js/ADMIN_all.js"></script>
</body>
</html>