<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Кафе "Огнище"</title>
    <link rel=stylesheet type=text/css href='css/all.css'>
    <link rel=stylesheet type=text/css href='css/index.css'>
    <link rel="shortcut icon" href="foto/iconka.png"/>
</head>
<body>
<div id="headerline_first">
    <div>
        <div class="text_headerline"><img class="icon" src="foto/icon_1.png">д. Балдеевка,<br>ул. Уличная, 17А</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_2.png">Пн-Сб: 11:00-23:00<br>Вс: 11:00-01:00</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_3.png">+375 (88) 435-26-91<br>+375 (32) 632-73-16</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_4.png">Instagram:<br>ognische_real</div>
        <button id="voiti_button" type="button"><img src="foto/icon_5.png">Войти</button>
    </div>
</div>
<div id="headerline_second">
    <div>
        <a class="a_headerline" href="menu">Меню</a>
        <a class="a_headerline" href="dostavka">Доставка и оплата</a>
        <a class="a_headerline" href="akcii">Акции</a>
        <a class="a_headerline" href="kontakty">Контакты</a>
        <a class="a_headerline" href="otzyvy">Отзывы</a>
    </div>
</div>
<a href="index"><img src="foto/logotip.png" id="logotip"></a>


<div id="index_fon_div">
    <img id="index_fon" src="foto/index_fon.png">
    <div id="nazvanie"><t1>Кафе-ресторан<br>«<t2>Огнище</t2>»</t1><hr><t3>Жарим что-надо!</t3></div>
    <div id="U_nas_v_menu_div"> <div id="U_nas_v_menu">У нас в меню</div> <div id="U_nas_v_menu_img"><img src="foto/strelka_1.png"></div> </div>
</div>

<table id="pictures">
    <tr>
        <td class="a1"><a href="menu"> <img src="foto/picture_1.png"> <div>Пицца</div> </a></td>
        <td class="a2"><a href="menu"> <img src="foto/picture_2.png"> <div>Бургеры</div> </a></td>
        <td class="a3"><a href="menu"> <img src="foto/picture_3.png"> <div>Гарниры</div> </a></td>
    </tr>
    <tr>
        <td class="a4"><a href="menu"> <img src="foto/picture_4.png"> <div>Шаурма</div> </a></td>
        <td class="a5"><a href="menu"> <img src="foto/picture_5.png"> <div>Салаты</div> </a></td>
        <td class="a6"><a href="menu"> <img src="foto/picture_6.png"> <div>Десерты</div> </a></td>
    </tr>
</table>

<div class="index_ssylka_1"><a class="index_ssylka" href="menu">&nbsp;Перейти в меню &#62;&nbsp;<hr></a> </div>

<div class="zagolovok zagolovok_1">Мы помогаем экономить</div>

<img src="foto/akcii/akcia_1.png" style="width: 80%; margin-left: 20%; margin-top: 20px;">
<img src="foto/akcii/akcia_2.png" style="width: 80%; margin-left: 35%; margin-top: 20px;">

<div class="index_ssylka_2"><a class="index_ssylka" href="akcii">&nbsp;Узнать<br>подробнее &#62;&nbsp;<hr></a> </div>

<div class="zagolovok zagolovok_2">Мы радуем покупателей</div>

<div id="otzyvvv">

    <div class="otzyv n1">
        <div class="name_i_zvezdy">
            <div class="name">Анастасия</div>
            <div class="zvezdy">
                <img class="z1" src="foto/zvezda_da.png">
                <img class="z2" src="foto/zvezda_da.png">
                <img class="z3" src="foto/zvezda_da.png">
                <img class="z4" src="foto/zvezda_da.png">
                <img class="z5" src="foto/zvezda_net.png">
            </div>
        </div>
        <div class="otzyv_text">Оч круто!!!! Но мало</div>
        <div class="data_i_ocenki">
            <div class="data">20.12.2022</div>
        </div>
    </div>

    <div class="otzyv n2">
        <div class="name_i_zvezdy">
            <div class="name">Анастасия</div>
            <div class="zvezdy">
                <img class="z1" src="foto/zvezda_da.png">
                <img class="z2" src="foto/zvezda_da.png">
                <img class="z3" src="foto/zvezda_da.png">
                <img class="z4" src="foto/zvezda_da.png">
                <img class="z5" src="foto/zvezda_net.png">
            </div>
        </div>
        <div class="otzyv_text">Оч круто!!!! Но мало</div>
        <div class="data_i_ocenki">
            <div class="data">20.12.2022</div>
        </div>
    </div>

    <div class="otzyv n3">
        <div class="name_i_zvezdy">
            <div class="name">Анастасия</div>
            <div class="zvezdy">
                <img class="z1" src="foto/zvezda_da.png">
                <img class="z2" src="foto/zvezda_da.png">
                <img class="z3" src="foto/zvezda_da.png">
                <img class="z4" src="foto/zvezda_da.png">
                <img class="z5" src="foto/zvezda_net.png">
            </div>
        </div>
        <div class="otzyv_text">Оч круто!!!! Но мало</div>
        <div class="data_i_ocenki">
            <div class="data">20.12.2022</div>
        </div>
    </div>
</div>

<div class="index_ssylka_3"><a class="index_ssylka" href="otzyvy">&nbsp;Читать отзывы &#62;&nbsp;<hr></a> </div>

<div class="zagolovok zagolovok_3">Мы находимся здесь</div>

<div class="teeext">
    <div class="index_ssylka_4"><a class="index_ssylka" href="kontakty">&nbsp;Смотреть карту &#62;&nbsp;<hr></a> </div>
</div>





<div><script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Af70efe4be5ee0324e9cf8595fab08219ed8fe93712dd3bbfebd200f1aaf6a833&amp;width=100%25&amp;height=624&amp;lang=ru_RU&amp;scroll=true"></script></div>

<div id="zatemnenie"></div>

<form id="voiti_okno" action="/index_authenticate" method="post">
    <div class="name"><div>Вход в аккаунт</div><hr></div>
    <div class="h2">
        <div>Логин</div>
        <input type="text" size="30" maxlength="30" name="login">
    </div>
    <div class="h2">
        <div>Пароль</div>
        <input type="text" size="30" maxlength="30" name="password">
    </div>
    <div class="soobshcenie">*Неправильный логин или пароль</div>
    <div class="butte_1">
        <button type="button" id="button_za_admin">Войти как администратор</button>
        <button type="submit" id="voiti_okno_voiti">Войти</button>
    </div>
    <div class="butte_2">
        <div>Или...</div>
        <button type="button" id="button_zareg">Регистрация</button>
    </div>
    <button type="button"  id="voiti_okno_button_cloze"><img src="foto/cloze.png" style="width: 25px;"></button>
</form>

<form id="registr_okno" action="/index_registration" method="post">
    <div class="name"><div>Регистрация</div><hr></div>
    <div class="h2">
        <div>Телефон</div>
        <input type="text" size="30" maxlength="30" name="phone">
    </div>
    <div class="h2">
        <div>Логин</div>
        <input type="text" size="30" maxlength="30" name="login">
    </div>
    <div class="h2">
        <div>Пароль</div>
        <input type="text" size="30" maxlength="30" name="password">
    </div>
    <div class="soobshcenie">*Неправильный логин или пароль</div>
    <div class="butte_1">
        <button type="submit" id="registr_okno_reg">Регистрация</button>
    </div>
    <div class="butte_2">
        <div>Или...</div>
        <button type="button" id="registr_okno_voiti">Войти</button>
    </div>
    <button type="button"  id="registr_okno_button_cloze"><img src="foto/cloze.png" style="width: 25px;"></button>
</form>

<form id="voiti_admin_okno" action="/index_authenticate_admin" method="post">
    <div class="name"><div>Вход в аккаунт</div><hr></div>
    <div class="h2">
        <div>Логин</div>
        <input type="text" size="30" maxlength="30" name="login">
    </div>
    <div class="h2">
        <div>Пароль</div>
        <input type="text" size="30" maxlength="30" name="password">
    </div>
    <div class="soobshcenie">*Неправильный логин или пароль</div>
    <div class="butte_1">
        <button type="button" id="button_za_polz">Войти как пользователь</button>
        <button type="submit" id="voiti_admin_okno_voiti">Войти</button>
    </div>
    <button type="button"  id="voiti_admin_okno_button_cloze"><img src="foto/cloze.png" style="width: 25px;"></button>
</form>

<div id="footerline" style="margin-top: 0px;">© 2006-2023 ООО &#171;Огнище&#187;. Все права защищены</div>

<script src="js/all.js"></script>
</body>
</html>