<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Кафе "Огнище"</title>
    <link rel=stylesheet type=text/css href='css/POLZOVATEL_all.css'>
    <link rel=stylesheet type=text/css href='css/POLZOVATEL_akcii.css'>
    <link rel="shortcut icon" href="foto/iconka.png" />
</head>
<body>
<div id="headerline_first">
    <div>
        <div class="text_headerline"><img class="icon" src="foto/icon_1.png">д. Балдеевка,<br>ул. Уличная, 17А</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_2.png">Пн-Сб: 11:00-23:00<br>Вс: 11:00-01:00</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_3.png">+375 (88) 435-26-91<br>+375 (32) 632-73-16</div>
        <div class="text_headerline"><img class="icon" src="foto/icon_4.png">Instagram:<br>ognische_real</div>
        <div class="headerline_buttons">
            <a href="POLZOVATEL_izbrannoe" id="voiti_izbr_button" style="margin-left: 0px;"><img src="foto/button_1.png" style="height: 21px"></a>
            <a href="POLZOVATEL_korzina" id="voiti_korz_button"><img src="foto/button_2.png" style="height: 25px"></a>
            <a href="POLZOVATEL_lichnyi_kabinet" id="voiti_acc_button"><img src="foto/button_3.png" style="height: 26px"></a>
        </div>
    </div>
</div>
<div id="headerline_second">
    <div>
        <a class="a_headerline" href="POLZOVATEL_menu">Меню</a>
        <a class="a_headerline" href="POLZOVATEL_dostavka">Доставка и оплата</a>
        <a class="a_headerline" href="POLZOVATEL_akcii">Акции</a>
        <a class="a_headerline" href="POLZOVATEL_kontakty">Контакты</a>
        <a class="a_headerline" href="POLZOVATEL_otzyvy">Отзывы</a>
    </div>
</div>
<a href="POLZOVATEL_index"><img src="foto/logotip.png" id="logotip"></a>

<div id="name"><a1></a1><div class="zagolovok zagolovok_6">Акции</div><a2></a2></div>

<div id="akcii_block">
    <img src="foto/akcii/akcia_1.png">
    <img src="foto/akcii/akcia_2.png">
    <img src="foto/akcii/akcia_3.png">
    <img src="foto/akcii/akcia_4.png">
    <img src="foto/akcii/akcia_5.png">
</div>

<div id="footerline">© 2006-2023 ООО &#171;Огнище&#187;. Все права защищены</div>

<script src="js/POLZOVATEL_all.js"></script>
</body>
</html>